### DISCUSSION TITLE
custom rules with multi-cluster support (Plugin API)

### DISCUSSION THREAD

**Discussion by calvinxu** [kubewharf/kelemetry#164] [Q&A] [answered]
Just wonder how to use "custom rules with multi-cluster support (Plugin API)" feature, does it mean that we can create custom rules, what are the rules refer here? 
and does this feature support require to use PluginAPI, which to be installed separately or what type of PluginAPI here?

**Comment by SOF3** [comment]
## 1. Annotation linker

Currently, you can link make objects declare their own parent without ownerReferences by writing the annotation `kelemetry.kubewharf.io/parent-link` on an object to point to its parent object with a JSON-encoded value in the [`ParentLink` schema](https://github.com/kubewharf/kelemetry/blob/b147c6c3c3a5ebce0c19960abbfa39276748f507/pkg/annotationlinker/schema.go#L24-L33).

## 2. Custom linker plugin

Alternatively, you may use [out-of-tree plugins](https://github.com/kubewharf/kelemetry/blob/main/docs/DEV.md#list-components) by building your own binary with `ProvideListImpl` on the `aggregator/linker.Linker` interface. For a TLDR, it means to create a file in your workspace like this:

```go
package main

import (
    "context"

    "github.com/kubewharf/kelemetry/cmd/kelemetry"
    "github.com/kubewharf/kelemetry/pkg/aggregator/linker"
    "github.com/kubewharf/kelemetry/pkg/manager"
    _ "github.com/kubewharf/kelemetry/pkg"
    "github.com/kubewharf/kelemetry/pkg/util"
)

type myLinker struct {
    manager.BaseComponent
}
func (*myLinker) Lookup(ctx context.Context, object util.ObjectRef) *util.ObjectRef {
    // compute new parent object reference from `object`
}

func init() {
    manager.Global.ProvideListImpl("my-linker", manager.Ptr(&myLinker{}), &manager.List[linker.Linker]{})
}

func main() {
    kelemetry.Main()
}
```

Then compile this binary in place of the official Kelemetry image.

## 3. LinkRule

There is a WIP feature in #109 (currently on hold to merge #157 first), which will allow dynamically defining link rules with [a CRD](https://github.com/kubewharf/kelemetry/pull/109/files#diff-0e52aa922f20327eb5997cfd30d0cb77823338841d4b94ab28c81e1e6ee0c5e3).

**Comment by calvinxu** [comment]
1. so for the 1. "....by writing the annotation kelemetry.kubewharf.io/parent-link on an object to point to its parent object with a JSON-encoded value in the [ParentLink schema]" is there an example can be referenced?
2. which means this need extra effort to implement this out-of-tree plugin, and place it into the kelemetry image to make it work?
3. How to understand "allow dynamically defining link rules with a CRD" in this feature?

**Comment by SOF3** [comment]
1. This feature is not very well-documented yet, because it is a bit awkward to use — you need to ensure the annotation is present when Kelemetry processes this object the first time (i.e. on creation), which means you need either a mutating webhook or to modify the controller that creates an object. Roughly speaking it looks like this:

```yaml
metadata:
  annotations:
    kelemetry.kubewharf.io/parent-link: |
      {"cluster": "the-cluster-name", "group": "apps", "version": "v1", "resource": "deployments", "namespace": "default", "name": "example"}
```

2. Yes, more cumbersome to implement, but most flexible since you can execute any Go code there.

3. In the current design for that feature, for example, to support linking helm-rendered objects to the helm secret, you can write a rule like this:

```yaml
apiVersion: kelemetry.kubewharf.io/v1alpha1
kind: LinkRule
metadata:
  name: 
filter:
  selector:
    matchLabels:
      app.kubernetes.io/managed-by: Helm
parent:
  group: ""
  version: v1
  resource: secrets
  scope: Namespaced
  nameTemplate: '{{.metadata.annotations["meta.helm.sh/release-name"]}}'
```

However the feature has not been completed yet and is subject to change.
