### ISSUE TITLE
frontend: Why the service deployment resource uses 2 identical storage services and wants to be optimized

### ISSUE THREAD

**Issue by jackwillsmith** [kubewharf/kelemetry#129]
### Description

frontend deployment mainfest

```yaml
...
      - command:
        - /usr/local/bin/kelemetry
        - --log-level=info
        - --pprof-enable=true
        - --jaeger-backend=jaeger-storage
        - --jaeger-cluster-names=cluster1
        - --jaeger-redirect-server-enable=true
        - --jaeger-storage-plugin-address=:17271   # localhost:17271
        - --jaeger-storage-plugin-enable=true
        - --jaeger-storage.grpc-storage.server=kelemetry-1689762474-storage.kelemetry.svc:17271   # storage-svc
        - --jaeger-storage.span-storage.type=grpc-plugin
        - --jaeger-trace-cache=etcd
        - --jaeger-trace-cache-etcd-endpoints=kelemetry-1689762474-etcd.kelemetry.svc:2379
        - --jaeger-trace-cache-etcd-prefix=/trace/
        - --trace-server-enable=true
        image: ghcr.io/kubewharf/kelemetry:0.1.0
...
```

### User story

It is convenient for users to be more familiar with the source code of the project
