### ISSUE TITLE
Audit log is not missed in the tracing data

### ISSUE THREAD

**Issue by calvinxu** [kubewharf/kelemetry#133]
### Steps to reproduce

    1. check out 0.2.2 tag from kelemetry repo
    2. helm install kelemetry oci://ghcr.io/kubewharf/kelemetry-chart --values values.yaml

### Expected behavior

on the Jaeger UI, when browsing the tracing data for a deployment/pod, it will event/audit data in the tracing data,

### Actual behavior

it only displays the event data

![image](https://github.com/kubewharf/kelemetry/assets/1214528/c9ca590b-8aab-4d0c-8caa-626e17bd3c9c)

it is quite odd, that the cluster is "foo", is it from a test value?
my audit-log setting is as below, enabled in the apiserver setting, not sure whether the setting for webhook is correct??? I followed somehow from the quickstart demo setting.

```
#cat audit-policy.yaml
apiVersion: audit.k8s.io/v1
kind: Policy
rules:
  - level: RequestResponse
```

```
# cat webhook-config.yaml
apiVersion: v1
clusters:
- cluster:
    server: http://10.200.112.184:8080/audit
  name: audit
contexts:
- context:
    cluster: audit
  name: main
current-context: main
kind: Config
preferences: {}
```

in quickstart deployment, event and audit data both displayed

![image](https://github.com/kubewharf/kelemetry/assets/1214528/f2c14631-a5f0-4ec1-a44d-b93bb1cb5edd)

### Kelemetry version

0.2.2

### Environment

k8s:1.23.17
Jaeger:1.4.2
